name: 'occam lumen'
on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.*'

        - name: Build
          run: |
            cd src/Client
            cp wwwroot/index.html wwwroot/404.html
            dotnet publish --configuration Release

        - name: Deploy
          if: ${{ github.ref == 'refs/heads/occamlumen' }}
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: src/Client/bin/Release/net6.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            # Custom Domain
            cname: occamlu.men
